#!/bin/sh

#   hcp_fix - wrapper script for FIX, for HCP pipelines
#
#   Stephen Smith, FMRIB Analysis Group
#
#   Copyright (C) 2012-2013 University of Oxford
#
#   SHCOPYRIGHT
#
#   Changes by Timothy B. Brown <tbbrown@wustl.edu>
#
#   1) Changes to support 7T ICAFIX processing based on changes originally made by Keith jamison <kjamison@umn.edu>
#   2) Changes to echo output messages to aid in debugging 
#   3) Changes to call version 3.14a of melodic instead of melodic in FSL distribution based on changes
#      originally made by Mohana Ramaratnam <mohanakannan9@gmail.com>

# Set this before calling hcp_fix instead, to make it more flexible
#FSL_FIXDIR=$( cd $(dirname $0) ; pwd)
export FSL_FIXDIR=/disk/HCP/pipeline/external/fix1.06

#export FSL_FIXDIR

# All fix settings are held in the settings.sh file - edit this file to suit your setup
. ${FSL_FIXDIR}/settings.sh

#############################################################

DEBUG="FALSE"

Debug() {
	msg="${1}"
	if [ "${DEBUG}" = "TRUE" ]; then
		echo "hcp_fix: DEBUG: ${msg}"
	fi
}

Inform() {
	msg="${1}"
	echo "hcp_fix: INFORM: ${msg}"
}

Error() {
	msg="${1}"
	echo "hcp_fix: ERROR: ${msg}"
}

Usage() {
    cat <<EOF

hcp_fix <4D_FMRI_data> <highpass> [<TrainingFile>]
  with <highpass> being the temporal highpass full-width (2*sigma) in seconds

e.g.   hcp_fix BOLD_REST1_RL/BOLD_REST1_RL.nii.gz 200

for detrending-like behaviour, set <highpass> to 2000

EOF
    exit 1
}

[ "$2" = "" ] && Usage

fmri=$1
cd `dirname $fmri`
fmri=`basename $fmri`
fmri=`$FSLDIR/bin/imglob $fmri`
[ `imtest $fmri` != 1 ] && echo No valid 4D_FMRI input file specified && exit 1
fmri_orig=$fmri

hp=$2

unset TrainingData
if [ $# -ge 3 ]; then
	TrainingData=$3
fi

tr=`$FSLDIR/bin/fslval $fmri pixdim4`

curdir=$PWD


Inform "processing FMRI file $fmri with highpass $hp"


echo "${FSLDIR}/bin/fslmaths $fmri -bptf $hptr -1 ${fmri}_hp$hp"

if [ $hp -gt 0 ] ; then
  Inform "running highpass"
  hptr=`echo "10 k $hp 2 / $tr / p" | dc -`
  ${FSLDIR}/bin/fslmaths $fmri -bptf $hptr -1 ${fmri}_hp$hp
  fmri=${fmri}_hp$hp
fi

Inform "running MELODIC"
mkdir -p ${fmri}.ica
Debug "About to run melodic: Contents of ${fmri}.ica follow"
if [ "${DEBUG}" = "TRUE" ] ; then
	ls -lRa ${fmri}.ica
fi

Debug "Modified version of melodic in use"
Debug "melodic located at: ${HOME}/pipeline_tools/fix1.06a/melodic used"
Debug "instead of melodic located at: ${FSLDIR}/bin/melodic"
Debug "Beginning of melodic version log"
if [ "${DEBUG}" = "TRUE" ] ; then
	%${HOME}/pipeline_tools/fix1.06a/melodic --version
    $FSLDIR/bin/melodic  --version
fi
Debug "End of melodic version log"


# "old" melodic command
echo $FSLDIR/bin/melodic -i $fmri -v -o ${fmri}.ica/filtered_func_data.ica -d -250 --nobet --report --Oall --tr=$tr

$FSLDIR/bin/melodic -i $fmri -v -o ${fmri}.ica/filtered_func_data.ica -d -250 --nobet --report --Oall --tr=$tr
#
#${FSL_FIXDIR}/melodic -i $fmri -o ${fmri}.ica/filtered_func_data.ica -d -250 --nobet --report --Oall --tr=$tr



retCode=$?
Debug "melodic has been run: retCode = ${retCode}"
Debug "melodic has been run: Contents of ${fmri}.ica follow"
if [ "${DEBUG}" = "TRUE" ] ; then
	ls -lRa ${fmri}.ica
fi



if [ "${retCode}" -ne "0" ] ; then
    Error "melodic has returned a non-zero code"
	Error "Exiting this script with -1 return value."
	exit -1
fi

cd $curdir/${fmri}.ica

$FSLDIR/bin/imln ../$fmri filtered_func_data
$FSLDIR/bin/imln filtered_func_data.ica/mask mask

if [ `$FSLDIR/bin/imtest ../${fmri_orig}_SBRef` = 1 ] ; then
  $FSLDIR/bin/imln ../${fmri_orig}_SBRef mean_func
else
  $FSLDIR/bin/imln filtered_func_data.ica/mean mean_func
fi

if [ -f ../${fmri_orig}_Atlas.dtseries.nii ] ; then
  $FSLDIR/bin/imln ../${fmri_orig}_Atlas.dtseries.nii Atlas.dtseries.nii
fi

mkdir -p mc
if [ -f ../Movement_Regressors.txt ] ; then
  cat ../Movement_Regressors.txt | awk '{ print $4 " " $5 " " $6 " " $1 " " $2 " " $3}' > mc/prefiltered_func_data_mcf.par
else
  Error "Movement_Regressors.txt not retrieved properly." 
  exit -1
fi 
