tbl= Xnat_get_all_data;

tbl.ID=[];
tbl.digest=[];
tbl.UID=[];
t=unique(tbl);
tbl.cat_id=[];
tbl.name=[];
tbl.xsi_type=[];
tbl.xnat_abstractresource_id=[];
tbl.file_size=[];
tbl.createdBy=[];
tbl.createdEventId=[];
tbl.element_name=[];
tbl.createdTime=[];
tbl.URI=[];
tbl.instanceNumber=[];
tbl.tags=[];
t=unique(tbl);


N={'AAHScout' 'AAHScout';...
'AAHScout_MPR_cor' [];...
'AAHScout_MPR_sag' [];...
'AAHScout_MPR_tra' [];...
'AAHead_Scout_64ch-head-coil' 'AAHScout';...
'AAHead_Scout_64ch-head-coil_MPR_cor' [];...
'AAHead_Scout_64ch-head-coil_MPR_sag' [];...
'AAHead_Scout_64ch-head-coil_MPR_tra' [];...
'ASL' 'ASL';...
'ASL_M0' [];...
'AXIAL RECONS' [];...
'BIAS_64CH' 'BIAS_64CH';...
'BIAS_BC' 'BIAS_BC';...
'BIAS_BC_20channel' 'BIAS_BC_20channel';...
'BIAS_BC_64CH' 'BIAS_64CH';...
'BOLD_LANGUAGE1_AP' 'BOLD_LANGUAGE1_AP';...
'BOLD_LANGUAGE1_AP_PhysioLog' [];...
'BOLD_LANGUAGE1_AP_SBRef' 'BOLD_LANGUAGE1_AP_SBRef';...
'BOLD_MOTOR1_AP' 'BOLD_MOTOR1_AP';...
'BOLD_MOTOR1_AP_PhysioLog' [];...
'BOLD_MOTOR1_AP_SBRef' 'BOLD_MOTOR1_AP_SBRef';...
'BOLD_MOTOR2_PA' 'BOLD_MOTOR2_PA';...
'BOLD_MOTOR2_PA_PhysioLog' [];...
'BOLD_MOTOR2_PA_SBRef' 'BOLD_MOTOR2_PA_SBRef';...
'BOLD_MOTOR2_PA_SBRef_repeat' [];...
'BOLD_REST1_AP_PhysioLog' [];...
'BOLD_REST1_PA_PhysioLog' [];...
'BOLD_REST2_AP_PhysioLog' [];...
'BOLD_REST2_PA_PhysioLog' [];...
'BOLD_REST1_AP' 'BOLD_REST_AP';...
'BOLD_REST1_AP_SBRef' 'BOLD_REST_AP_SBRef';...
'BOLD_REST2_AP' 'BOLD_REST_AP';...
'BOLD_REST2_AP_SBRef' 'BOLD_REST_AP_SBRef';...
'BOLD_REST3_AP' 'BOLD_REST_AP';...
'BOLD_REST3_AP_SBRef' 'BOLD_REST_AP_SBRef';...
'BOLD_REST4_AP' 'BOLD_REST_AP';...
'BOLD_REST4_AP_SBRef' 'BOLD_REST_AP_SBRef';...
'BOLD_REST1_PA' 'BOLD_REST_PA';...
'BOLD_REST1_PA_SBRef' 'BOLD_REST_PA_SBRef';...
'BOLD_REST2_PA' 'BOLD_REST_PA';...
'BOLD_REST2_PA_SBRef' 'BOLD_REST_PA_SBRef';...
'BOLD_REST3_PA' 'BOLD_REST_PA';...
'BOLD_REST3_PA_SBRef' 'BOLD_REST_PA_SBRef';...
'BOLD_REST4_PA' 'BOLD_REST_PA';...
'BOLD_REST4_PA_SBRef' 'BOLD_REST_PA_SBRef';...
'BOLD_REST3_AP' 'BOLD_REST_AP';...
'BOLD_REST3_AP_PhysioLog' [];...
'BOLD_REST3_AP_SBRef' 'BOLD_REST_AP_SBRef';...
'BOLD_REST3_PA' 'BOLD_REST_PA';...
'BOLD_REST3_PA_PhysioLog' [];...
'BOLD_REST3_PA_SBRef' 'BOLD_REST_PA_SBRef';...
'BOLD_REST4_AP' 'BOLD_REST_AP';...
'BOLD_REST4_AP_PhysioLog' [];...
'BOLD_REST4_AP_SBRef' 'BOLD_REST_AP_SBRef';...
'BOLD_REST4_PA' 'BOLD_REST_PA';...
'BOLD_REST4_PA_PhysioLog' [];...
'BOLD_REST4_PA_SBRef' 'BOLD_REST_PA_SBRef';...
'BOLD_WM1_AP_PhysioLog' [];...
'BOLD_WM2_PA_PhysioLog' [];...
'DWI_dir98_AP' 'DWI_dir98_AP';...
'DWI_dir98_AP_SBRef' 'DWI_dir98_AP_SBRef';...
'DWI_dir98_PA' 'DWI_dir98_PA';...
'DWI_dir98_PA_SBRef' 'DWI_dir98_PA_SBRef';...
'DWI_dir99_AP' 'DWI_dir99_AP';...
'DWI_dir99_AP_SBRef' 'DWI_dir99_AP_SBRef';...
'DWI_dir99_PA' 'DWI_dir99_PA';...
'DWI_dir99_PA_SBRef' 'DWI_dir99_PA_SBRef';...
'FieldMap' 'FieldMap';...
'FieldMap_Magnitude' 'FieldMap_Magnitude';...
'FieldMap_Phase' 'FieldMap_Phase';...
'HighSpeed_SB' [];...
'Localizer' 'Localizer';...
'Localizer_aligned' 'Localizer_aligned';...
'MEG_EMPTY' 'MEG_EMPTY';...
'PET PiB Brain BP_All Pass 256_3.09Z_No match CT' 'PET PiB';...
'Perfusion_Weighted' [];...
'PhoenixZIPReport' [];...
'SWI_Images' 'SWI_Images';...
'SpinEchoFieldMap_AP' 'SpinEchoFieldMap_AP';...
'SpinEchoFieldMap_PA' 'SpinEchoFieldMap_PA';...
'T1w_MPR' 'T1w_MPR';...
'T2w_FLAIR' 'T2w_FLAIR';...
'T2w_SPC' 'T2w_SPC';...
'TOF_Limited_FOV' [];...
'TOF_Limited_FOV_MIP_COR' [];...
'TOF_Limited_FOV_MIP_SAG' [];...
'TOF_Limited_FOV_MIP_TRA' [];...
'ax recon' [];...
'cor recon' [];...
'dMRI_dir98_AP' 'DWI_dir98_AP';...
'dMRI_dir98_AP_SBRef' 'DWI_dir98_AP_SBRef';...
'dMRI_dir98_PA' 'DWI_dir98_PA';...
'dMRI_dir98_PA_SBRef' 'DWI_dir98_PA_SBRef';...
'dMRI_dir99_AP' 'DWI_dir99_AP';...
'dMRI_dir99_AP_SBRef' 'DWI_dir99_AP_SBRef';...
'dMRI_dir99_PA' 'DWI_dir99_PA';...
'dMRI_dir99_PA_SBRef' 'DWI_dir99_PA_SBRef';...
'ep2d_mb_pasl_scout20' [];...
'ep2d_mb_pasl_scout24' [];...
'localizer  manually start physio' 'Localizer';...
'mIP_Images(SW)' [];...
'rfMEG_REST' 'rfMEG_REST';...
'rfMRI_REST1_AP' 'BOLD_REST_AP';...
'rfMRI_REST1_AP_SBRef' 'BOLD_REST_AP_SBRef';...
'rfMRI_REST1_PA' 'BOLD_REST_PA';...
'rfMRI_REST1_PA_SBRef' 'BOLD_REST_PA_SBRef';...
'rfMRI_REST2_AP' 'BOLD_REST_AP';...
'rfMRI_REST2_AP_SBRef' 'BOLD_REST_AP_SBRef';...
'rfMRI_REST2_PA' 'BOLD_REST_PA';...
'rfMRI_REST2_PA_SBRef' 'BOLD_REST_PA_SBRef';...
'rfMRI_REST3_AP' 'BOLD_REST_AP';...
'rfMRI_REST_AP' 'BOLD_REST_AP';...
'rfMRI_REST_AP_SBRef' 'BOLD_REST_AP_SBRef';...
'rfMRI_REST_PA' 'BOLD_REST_PA';...
'rfMRI_REST_PA_SBRef' 'BOLD_REST_PA_SBRef';...
'rfMRI_WM1_AP_SBRef' 'BOLD_WM1_AP_SBRef';...
't1_tse_fs_tra_' [];...
'tfMEG_LANGUAGE1' 'tfMEG_LANGUAGE1';...
'tfMEG_LANGUAGE2' 'tfMEG_LANGUAGE2';...
'tfMEG_MOTOR1' 'tfMEG_MOTOR1';...
'tfMEG_MOTOR2' 'tfMEG_MOTOR2';...
'tfMEG_WM1' 'tfMEG_WM1';...
'tfMEG_WM2' 'tfMEG_WM2';...
'tfMRI_LANGUAGE1_AP' 'BOLD_LANGUAGE1_AP';...
'tfMRI_LANGUAGE1_AP.txt' [];...
'tfMRI_LANGUAGE1_AP_SBRef' 'BOLD_LANGUAGE1_AP_SBRef';...
'tfMRI_LANGUAGE2_PA' 'BOLD_LANGUAGE2_PA';...
'tfMRI_LANGUAGE2_PA_SBRef' 'BOLD_LANGUAGE2_PA_SBRef';...
'tfMRI_MOTOR1_AP' 'BOLD_MOTOR1_AP';...
'tfMRI_MOTOR1_AP.edat2' [];...
'tfMRI_MOTOR1_AP_SBRef' 'BOLD_MOTOR1_AP_SBRef';...
'tfMRI_MOTOR2_PA' 'BOLD_MOTOR2_PA';...
'tfMRI_MOTOR2_PA.edat2' [];...
'tfMRI_MOTOR2_PA_SBRef' 'BOLD_MOTOR2_PA_SBRef';...
'tfMRI_WM1_AP' 'BOLD_WM1_AP';...
'tfMRI_WM1_AP.edat2' [];...
'tfMRI_WM1_AP_SBRef' 'BOLD_WM1_AP_SBRef';...
'tfMRI_WM2_PA' 'BOLD_WM2_PA';...
'tfMRI_WM2_PA.edat2' [];...
'tfMRI_WM2_PA_SBRef' 'BOLD_WM2_PA_SBRef';...
'vessel_scout_head_MSUM' [];...
'vessel_scout_head_MSUM_MIP_SAG' []};


for i=1:length(N)
    lst=find(ismember(t.cat_desc,N{i,1}));
    for j=1:length(lst)
        if(isempty(N{i,2}))
             t.cat_desc{lst(j)}=' ';
        else
        t.cat_desc{lst(j)}=N{i,2};
        end
    end
end
    
t(ismember(t.cat_desc,' '),:)=[];


s=struct;
s.desc=unique(t.cat_desc);
subj=unique(t.Var1);
for i=1:length(subj); 
    tt=zeros(length(s.desc),1); 
    for j=1:length(s.desc); 
        lst=find(ismember(t.Var1,subj{i}) & ismember(t.cat_desc,s.desc{j}));
        if(~isempty(lst)); 
            tt(j)=sum(t.file_count(lst)); 
        end; 
    end; 
    s=setfield(s,subj{i},tt);
end;


nirs.util.write_xls('Xnat_upload_3-11-19.xlsx',struct2table(s))

