% Run HCP_characterize_connectivity_alldays_wmh.m first

%% This section implements Ted's lme WMH analysis by network (only DMN for now)

SN_regions = {'Visual1', 'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Visual2',...
'Visual2', 'Somatomotor', 'Somatomotor', 'Cingulo-Oper',...
'Language', 'Default', 'Visual2', 'Frontopariet', 'Frontopariet',...
'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Visual2',...
'Visual2', 'Visual2', 'Auditory', 'Default', 'Default',...
'Dorsal-atten', 'Default', 'Frontopariet', 'Posterior-Mu',...
'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
'Posterior-Mu', 'Somatomotor', 'Cingulo-Oper', 'Cingulo-Oper',...
'Somatomotor', 'Somatomotor', 'Somatomotor', 'Somatomotor',...
'Cingulo-Oper', 'Cingulo-Oper', 'Cingulo-Oper', 'Language',...
'Somatomotor', 'Visual2', 'Visual2', 'Language', 'Somatomotor',...
'Somatomotor', 'Somatomotor', 'Somatomotor', 'Somatomotor',...
'Somatomotor', 'Cingulo-Oper', 'Cingulo-Oper', 'Cingulo-Oper',...
'Cingulo-Oper', 'Posterior-Mu', 'Posterior-Mu', 'Frontopariet',...
'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
'Posterior-Mu', 'Frontopariet', 'Default', 'Default',...
'Posterior-Mu', 'Frontopariet', 'Cingulo-Oper', 'Default',...
'Frontopariet', 'Default', 'Frontopariet', 'Frontopariet',...
'Cingulo-Oper', 'Frontopariet', 'Cingulo-Oper', 'Posterior-Mu',...
'Posterior-Mu', 'Frontopariet', 'Posterior-Mu', 'Frontopariet',...
'Frontopariet', 'Posterior-Mu', 'Posterior-Mu', 'Language',...
'Language', 'Frontopariet', 'Frontopariet', 'Cingulo-Oper',...
'Somatomotor', 'Somatomotor', 'Somatomotor', 'Auditory',...
'Auditory', 'Cingulo-Oper', 'Cingulo-Oper', 'Auditory',...
'Cingulo-Oper', 'Cingulo-Oper', 'Orbito-Affec', 'Frontopariet',...
'Orbito-Affec', 'Cingulo-Oper', 'Cingulo-Oper', 'Somatomotor',...
'Language', 'Language', 'Posterior-Mu', 'Posterior-Mu',...
'Posterior-Mu', 'Visual1', 'Ventral-Mult', 'Default', 'Auditory',...
'Default', 'Posterior-Mu', 'Language', 'Default', 'Default',...
'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Frontopariet',...
'Posterior-Mu', 'Ventral-Mult', 'Language', 'Language', 'Visual2',...
'Default', 'Dorsal-atten', 'Dorsal-atten', 'Visual1', 'Language',...
'Frontopariet', 'Frontopariet', 'Language', 'Cingulo-Oper',...
'Cingulo-Oper', 'Frontopariet', 'Posterior-Mu', 'Posterior-Mu',...
'Visual2', 'Visual2', 'Visual2', 'Posterior-Mu', 'Visual2',...
'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Posterior-Mu',...
'Posterior-Mu', 'Visual2', 'Posterior-Mu', 'Posterior-Mu',...
'Orbito-Affec', 'Cingulo-Oper', 'Somatomotor', 'Cingulo-Oper',...
'Frontopariet', 'Frontopariet', 'Default', 'Auditory', 'Auditory',...
'Auditory', 'Posterior-Mu', 'Posterior-Mu', 'Cingulo-Oper',...
'Cingulo-Oper', 'Cingulo-Oper', 'Visual1', 'Visual2', 'Visual2',...
'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Somatomotor',...
'Somatomotor', 'Cingulo-Oper', 'Cingulo-Oper', 'Default',...
'Visual2', 'Frontopariet', 'Frontopariet', 'Visual2', 'Visual2',...
'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Visual2',...
'Auditory', 'Cingulo-Oper', 'Default', 'Dorsal-atten',...
'Dorsal-atten', 'Frontopariet', 'Posterior-Mu', 'Posterior-Mu',...
'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
'Somatomotor', 'Cingulo-Oper', 'Cingulo-Oper', 'Somatomotor',...
'Somatomotor', 'Somatomotor', 'Somatomotor', 'Cingulo-Oper',...
'Cingulo-Oper', 'Cingulo-Oper', 'Language', 'Somatomotor',...
'Visual2', 'Visual2', 'Language', 'Somatomotor', 'Somatomotor',...
'Somatomotor', 'Somatomotor', 'Somatomotor', 'Somatomotor',...
'Cingulo-Oper', 'Frontopariet', 'Cingulo-Oper', 'Cingulo-Oper',...
'Posterior-Mu', 'Frontopariet', 'Frontopariet', 'Posterior-Mu',...
'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
'Frontopariet', 'Frontopariet', 'Default', 'Posterior-Mu',...
'Frontopariet', 'Cingulo-Oper', 'Default', 'Frontopariet',...
'Frontopariet', 'Cingulo-Oper', 'Frontopariet', 'Cingulo-Oper',...
'Frontopariet', 'Cingulo-Oper', 'Posterior-Mu', 'Posterior-Mu',...
'Frontopariet', 'Posterior-Mu', 'Frontopariet', 'Frontopariet',...
'Frontopariet', 'Posterior-Mu', 'Language', 'Language',...
'Frontopariet', 'Frontopariet', 'Cingulo-Oper', 'Somatomotor',...
'Somatomotor', 'Somatomotor', 'Auditory', 'Somatomotor',...
'Cingulo-Oper', 'Cingulo-Oper', 'Auditory', 'Cingulo-Oper',...
'Cingulo-Oper', 'Orbito-Affec', 'Frontopariet', 'Orbito-Affec',...
'Cingulo-Oper', 'Cingulo-Oper', 'Somatomotor', 'Language',...
'Language', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
'Visual1', 'Ventral-Mult', 'Default', 'Auditory', 'Default',...
'Posterior-Mu', 'Language', 'Posterior-Mu', 'Default',...
'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Frontopariet',...
'Posterior-Mu', 'Ventral-Mult', 'Language', 'Language', 'Visual2',...
'Default', 'Dorsal-atten', 'Dorsal-atten', 'Visual1', 'Language',...
'Frontopariet', 'Frontopariet', 'Language', 'Cingulo-Oper',...
'Cingulo-Oper', 'Frontopariet', 'Posterior-Mu', 'Posterior-Mu',...
'Visual2', 'Visual2', 'Visual2', 'Posterior-Mu', 'Visual2',...
'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Posterior-Mu',...
'Frontopariet', 'Visual2', 'Posterior-Mu', 'Posterior-Mu',...
'Orbito-Affec', 'Cingulo-Oper', 'Somatomotor', 'Cingulo-Oper',...
'Frontopariet', 'Frontopariet', 'Default', 'Auditory', 'Auditory',...
'Auditory', 'Posterior-Mu', 'Frontopariet', 'Cingulo-Oper',...
'Cingulo-Oper', 'Cingulo-Oper'...
'Subcort', 'Subcort', 'Subcort', 'Subcort', 'Subcort', 'Subcort'...
'Subcort', 'Subcort', 'Subcort', 'Subcort', 'Subcort', 'Subcort'};

% networks = unique(RSN_regions);
networks = {'Default','Frontopariet','Dorsal-atten'};
networks = {'Subcort'};
for n = 1:length(networks)
    net = networks{n};
    % Why are there NaNs in WMH matrices?
    wmh_stack(isnan(wmh_stack)) = 0;
    
    
    idx = ismember(RSN_regions,net);
    
    fc_RSN = fconn_stack_all_raw_ar(idx,idx,:);
    dti_RSN = dconn_stack(idx,idx,:);
    wmh_RSN = wmh_stack(idx,idx,:);
    idx_ut = logical(triu(ones(sum(idx)),1));
    numEdge = sum(idx_ut(:));
    
    % Mean subtract twice to avoid roundoff issues
    mean_fc = mean(fc_RSN,3);
    mean_dti = mean(dti_RSN,3);
    mean_wmh = mean(wmh_RSN,3);
    for i = 1:numSubj
        fc_RSN(:,:,i) = fc_RSN(:,:,i) - mean_fc;
        dti_RSN(:,:,i) = dti_RSN(:,:,i) - mean_dti;
        wmh_RSN(:,:,i) = wmh_RSN(:,:,i) - mean_wmh;
    end
    mean_fc = mean(fc_RSN,3);
    mean_dti = mean(dti_RSN,3);
    mean_wmh = mean(wmh_RSN,3);
    for i = 1:numSubj
        fc_RSN(:,:,i) = fc_RSN(:,:,i) - mean_fc;
        dti_RSN(:,:,i) = dti_RSN(:,:,i) - mean_dti;
        wmh_RSN(:,:,i) = wmh_RSN(:,:,i) - mean_wmh;
    end
    
    datastruct = struct;
    datastruct.subject = cell(numEdge*numSubj,1);
    datastruct.edge = nan(numEdge*numSubj,1);
    datastruct.net = cell(numEdge*numSubj,1);
    datastruct.DTI= nan(numEdge*numSubj,1);
    datastruct.WMH = nan(numEdge*numSubj,1);
    datastruct.F = nan(numEdge*numSubj,1);
    
    for s = 1:numSubj
        
        w = wmh_RSN(:,:,s); w = w(idx_ut);
        d = dti_RSN(:,:,s); d = d(idx_ut);
        f = fc_RSN(:,:,s); f = f(idx_ut);
        
        for e = 1:numEdge
            
            datastruct.subject{ (s-1)*numEdge + e } = have_conn{s};
            datastruct.edge( (s-1)*numEdge + e ) = e;
            datastruct.net{ (s-1)*numEdge + e } = net;
            datastruct.F( (s-1)*numEdge + e ) = f(e);
            datastruct.WMH( (s-1)*numEdge + e ) = w(e);
            datastrcut.DTI( (s-1)*numEdge + e ) = d(e);
            
        end
        
    end
end

datastruct.subject = categorical(datastruct.subject);
datastruct.edge = categorical(datastruct.edge );
tbl = struct2table(datastruct);