% Run HCP_characterize_connectivity_alldays.m first

% idx_sc = zeros(372);
% idx_sc(361:end,:) = 1;
% idx_sc(:,361:end) = 1;
% idx_sc = logical(idx_sc);
% idx_sc = logical(idx_sc.*idx_ut);


RSN_regions = {'Visual1', 'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Visual2',...
       'Visual2', 'Somatomotor', 'Somatomotor', 'Cingulo-Oper',...
       'Language', 'Default', 'Visual2', 'Frontopariet', 'Frontopariet',...
       'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Visual2',...
       'Visual2', 'Visual2', 'Auditory', 'Default', 'Default',...
       'Dorsal-atten', 'Default', 'Frontopariet', 'Posterior-Mu',...
       'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
       'Posterior-Mu', 'Somatomotor', 'Cingulo-Oper', 'Cingulo-Oper',...
       'Somatomotor', 'Somatomotor', 'Somatomotor', 'Somatomotor',...
       'Cingulo-Oper', 'Cingulo-Oper', 'Cingulo-Oper', 'Language',...
       'Somatomotor', 'Visual2', 'Visual2', 'Language', 'Somatomotor',...
       'Somatomotor', 'Somatomotor', 'Somatomotor', 'Somatomotor',...
       'Somatomotor', 'Cingulo-Oper', 'Cingulo-Oper', 'Cingulo-Oper',...
       'Cingulo-Oper', 'Posterior-Mu', 'Posterior-Mu', 'Frontopariet',...
       'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
       'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
       'Posterior-Mu', 'Frontopariet', 'Default', 'Default',...
       'Posterior-Mu', 'Frontopariet', 'Cingulo-Oper', 'Default',...
       'Frontopariet', 'Default', 'Frontopariet', 'Frontopariet',...
       'Cingulo-Oper', 'Frontopariet', 'Cingulo-Oper', 'Posterior-Mu',...
       'Posterior-Mu', 'Frontopariet', 'Posterior-Mu', 'Frontopariet',...
       'Frontopariet', 'Posterior-Mu', 'Posterior-Mu', 'Language',...
       'Language', 'Frontopariet', 'Frontopariet', 'Cingulo-Oper',...
       'Somatomotor', 'Somatomotor', 'Somatomotor', 'Auditory',...
       'Auditory', 'Cingulo-Oper', 'Cingulo-Oper', 'Auditory',...
       'Cingulo-Oper', 'Cingulo-Oper', 'Orbito-Affec', 'Frontopariet',...
       'Orbito-Affec', 'Cingulo-Oper', 'Cingulo-Oper', 'Somatomotor',...
       'Language', 'Language', 'Posterior-Mu', 'Posterior-Mu',...
       'Posterior-Mu', 'Visual1', 'Ventral-Mult', 'Default', 'Auditory',...
       'Default', 'Posterior-Mu', 'Language', 'Default', 'Default',...
       'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Frontopariet',...
       'Posterior-Mu', 'Ventral-Mult', 'Language', 'Language', 'Visual2',...
       'Default', 'Dorsal-atten', 'Dorsal-atten', 'Visual1', 'Language',...
       'Frontopariet', 'Frontopariet', 'Language', 'Cingulo-Oper',...
       'Cingulo-Oper', 'Frontopariet', 'Posterior-Mu', 'Posterior-Mu',...
       'Visual2', 'Visual2', 'Visual2', 'Posterior-Mu', 'Visual2',...
       'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Posterior-Mu',...
       'Posterior-Mu', 'Visual2', 'Posterior-Mu', 'Posterior-Mu',...
       'Orbito-Affec', 'Cingulo-Oper', 'Somatomotor', 'Cingulo-Oper',...
       'Frontopariet', 'Frontopariet', 'Default', 'Auditory', 'Auditory',...
       'Auditory', 'Posterior-Mu', 'Posterior-Mu', 'Cingulo-Oper',...
       'Cingulo-Oper', 'Cingulo-Oper', 'Visual1', 'Visual2', 'Visual2',...
       'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Somatomotor',...
       'Somatomotor', 'Cingulo-Oper', 'Cingulo-Oper', 'Default',...
       'Visual2', 'Frontopariet', 'Frontopariet', 'Visual2', 'Visual2',...
       'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Visual2',...
       'Auditory', 'Cingulo-Oper', 'Default', 'Dorsal-atten',...
       'Dorsal-atten', 'Frontopariet', 'Posterior-Mu', 'Posterior-Mu',...
       'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
       'Somatomotor', 'Cingulo-Oper', 'Cingulo-Oper', 'Somatomotor',...
       'Somatomotor', 'Somatomotor', 'Somatomotor', 'Cingulo-Oper',...
       'Cingulo-Oper', 'Cingulo-Oper', 'Language', 'Somatomotor',...
       'Visual2', 'Visual2', 'Language', 'Somatomotor', 'Somatomotor',...
       'Somatomotor', 'Somatomotor', 'Somatomotor', 'Somatomotor',...
       'Cingulo-Oper', 'Frontopariet', 'Cingulo-Oper', 'Cingulo-Oper',...
       'Posterior-Mu', 'Frontopariet', 'Frontopariet', 'Posterior-Mu',...
       'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
       'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
       'Frontopariet', 'Frontopariet', 'Default', 'Posterior-Mu',...
       'Frontopariet', 'Cingulo-Oper', 'Default', 'Frontopariet',...
       'Frontopariet', 'Cingulo-Oper', 'Frontopariet', 'Cingulo-Oper',...
       'Frontopariet', 'Cingulo-Oper', 'Posterior-Mu', 'Posterior-Mu',...
       'Frontopariet', 'Posterior-Mu', 'Frontopariet', 'Frontopariet',...
       'Frontopariet', 'Posterior-Mu', 'Language', 'Language',...
       'Frontopariet', 'Frontopariet', 'Cingulo-Oper', 'Somatomotor',...
       'Somatomotor', 'Somatomotor', 'Auditory', 'Somatomotor',...
       'Cingulo-Oper', 'Cingulo-Oper', 'Auditory', 'Cingulo-Oper',...
       'Cingulo-Oper', 'Orbito-Affec', 'Frontopariet', 'Orbito-Affec',...
       'Cingulo-Oper', 'Cingulo-Oper', 'Somatomotor', 'Language',...
       'Language', 'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu',...
       'Visual1', 'Ventral-Mult', 'Default', 'Auditory', 'Default',...
       'Posterior-Mu', 'Language', 'Posterior-Mu', 'Default',...
       'Posterior-Mu', 'Posterior-Mu', 'Posterior-Mu', 'Frontopariet',...
       'Posterior-Mu', 'Ventral-Mult', 'Language', 'Language', 'Visual2',...
       'Default', 'Dorsal-atten', 'Dorsal-atten', 'Visual1', 'Language',...
       'Frontopariet', 'Frontopariet', 'Language', 'Cingulo-Oper',...
       'Cingulo-Oper', 'Frontopariet', 'Posterior-Mu', 'Posterior-Mu',...
       'Visual2', 'Visual2', 'Visual2', 'Posterior-Mu', 'Visual2',...
       'Visual2', 'Visual2', 'Visual2', 'Visual2', 'Posterior-Mu',...
       'Frontopariet', 'Visual2', 'Posterior-Mu', 'Posterior-Mu',...
       'Orbito-Affec', 'Cingulo-Oper', 'Somatomotor', 'Cingulo-Oper',...
       'Frontopariet', 'Frontopariet', 'Default', 'Auditory', 'Auditory',...
       'Auditory', 'Posterior-Mu', 'Frontopariet', 'Cingulo-Oper',...
       'Cingulo-Oper', 'Cingulo-Oper'...
       'Subcort', 'Subcort', 'Subcort', 'Subcort', 'Subcort', 'Subcort'...
       'Subcort', 'Subcort', 'Subcort', 'Subcort', 'Subcort', 'Subcort'};

   unique_RSN = unique(RSN_regions);
   
for r = 1:length(unique_RSN)
    idx_RSN = ismember(RSN_regions,unique_RSN(r));
    
    fconn_RSN = fconn_stack_all_raw_ar(idx_RSN,idx_RSN,:);
    dconn_RSN = dconn_stack(idx_RSN,idx_RSN,:);
    wmh_RSN = wmh_stack(idx_RSN,idx_RSN,:);

    idx_ut = logical( triu( ones( size(fconn_RSN ,1) ) ,1) );

numSubj = size(fconn_RSN,3);
numEdge = sum(idx_ut(:));

beta_WMH = nan(numEdge,1);
beta_DTI = nan(numEdge,1);
t_WMH = nan(numEdge,1);
t_DTI = nan(numEdge,1);
p_WMH = nan(numEdge,1);
p_DTI = nan(numEdge,1);
frac_WMH = nan(numEdge,1);
frac_DTI = nan(numEdge,1);

% Why are there NaNs in WMH matrices?
wmh_RSN(isnan(wmh_RSN)) = 0;


% Extract subj-by-edge wmh, dti, and fc
fc = []; dti = []; wmh = [];
for i = 1:numSubj
    f = atanh(fconn_RSN(:,:,i));
    d = dconn_RSN(:,:,i);
    w = wmh_RSN(:,:,i);
    fc = [fc ; f(idx_ut)'];
    dti = [dti ; d(idx_ut)'];
    wmh = [wmh ; w(idx_ut)'];
end

for i = 1:numEdge
    y = fc(:,i);
    x = [ dti(:,i) wmh(:,i)];
    if rank(x) == size(x,2) %  & sum(x(:,1)>0)>0.5*length(y) % & sum(x(:,2)>0)>0.75*length(y)
        mdl = fitlm(x,y);
        beta_WMH(i) = mdl.Coefficients.Estimate(3);
        beta_DTI(i) = mdl.Coefficients.Estimate(2);
        frac_WMH(i) = sum(x(:,2)>0) / length(y);
        frac_DTI(i) = sum(x(:,1)>0) / length(y);
        t_WMH(i) = mdl.Coefficients.tStat(3);
        t_DTI(i) = mdl.Coefficients.tStat(2);
        p_WMH(i) = mdl.Coefficients.pValue(3);
        p_DTI(i) = mdl.Coefficients.pValue(2);
        disp([num2str(i) ' of ' num2str(numEdge) ' completed.' ])
    else
        disp([num2str(i) ' of ' num2str(numEdge) ' skipped.' ])

    end
end


p_mat_DTI = triu(ones(size(d)),1);
p_mat_DTI(p_mat_DTI==1)=p_DTI;
p_mat_DTI = p_mat_DTI + p_mat_DTI';
p_mat_WMH = triu(ones(size(d)),1);
p_mat_WMH(p_mat_WMH==1)=p_WMH;
p_mat_WMH = p_mat_WMH + p_mat_WMH';

k = frac_DTI>0.5;

figure(1)
subplot(5,3,r);
hist(t_DTI(k))
title(sprintf([unique_RSN{r} '\nn=' num2str(sum(~isnan(t_DTI(k)))) ', mean=' num2str(nanmean(t_DTI(k))) '\n+beta=' num2str(sum(t_DTI(k)>0 & p_DTI(k)<0.05)) ', -beta=' num2str(sum(t_DTI(k)<0 & p_DTI(k)<0.05))]))
drawnow
figure(2)
subplot(5,3,r);
hist(t_WMH(k))
title(sprintf([unique_RSN{r} '\nn=' num2str(sum(~isnan(t_WMH(k)))) ', mean=' num2str(nanmean(t_WMH(k))) '\n+beta=' num2str(sum(t_WMH(k)>0 & p_WMH(k)<0.05)) ', -beta=' num2str(sum(t_WMH(k)<0 & p_WMH(k)<0.05))]))
drawnow
end