function PCA_processing(subjid,outfolder,force)

if(nargin<3)
    force=false;
end
if(nargin<2)
    outfolder='/aionraid/huppertt/XnatDB/ROS-MOVE';
end

if(~force & exist(fullfile(outfolder,subjid,'PCA','PCA_vessels_MNI.nii.gz'))==2)
    return
end

system(['mkdir -p ' outfolder filesep subjid filesep 'PCA']);

f=fullfile(outfolder,subjid,'unprocessed','3T','PCA',[subjid '_3T_flow_pc3d_sag_venc10_sinus.nii.gz']);
copyfile(f,fullfile(outfolder,subjid,'PCA','PCA_head.nii.gz'));

f=fullfile(outfolder,subjid,'unprocessed','3T','PCA',[subjid '_3T_flow_pc3d_sag_venc10_sinus_MSUM.nii.gz']);
copyfile(f,fullfile(outfolder,subjid,'PCA','PCA_vessels.nii.gz'));

copyfile(fullfile(outfolder,subjid,'T1w','T1w.nii.gz'),...
    fullfile(outfolder,subjid,'PCA','T1w.nii.gz'));

% Aligns PCA to T1w (xfm = PCA2T1w.mat)
system(['flirt '...
    '-in    ' fullfile(outfolder,subjid,'PCA','PCA_head.nii.gz')...
    ' -ref  ' fullfile(outfolder,subjid,'PCA','T1w.nii.gz')...
    ' -out  ' fullfile(outfolder,subjid,'PCA','PCA_head_registered.nii.gz')...
    ' -omat ' fullfile(outfolder,subjid,'PCA','PCA2T1w.mat')...
    ' -dof 6']);

% Warps T1-aligned PCA into MNI space
system(['applywarp '...
    ' -i ' fullfile(outfolder,subjid,'PCA','PCA_head_registered.nii.gz') ...
    ' -r ' fullfile(outfolder,subjid,'T1w','T1w_acpc_dc_restore.nii.gz') ...
    ' --premat=' fullfile(outfolder,subjid,'T1w','xfms','acpc.mat') ...
    ' --warp=' fullfile(outfolder,subjid,'T1w','BrainExtraction_FNIRTbased','str2standard.nii.gz') ...
    ' -o ' fullfile(outfolder,subjid,'PCA','PCA_head_MNI.nii.gz')]);

% Moves PCA vessels resolution of PCA_head_registered? (Not sure what it 
% means to call applywarp with no warp file specified)
system(['applywarp ' ...
    ' -i ' fullfile(outfolder,subjid,'PCA','PCA_vessels.nii.gz') ...
    ' -r ' fullfile(outfolder,subjid,'PCA','PCA_head_registered.nii.gz') ...
    ' --premat=' fullfile(outfolder,subjid,'PCA','PCA2T1w.mat') ...
    ' -o ' fullfile(outfolder,subjid,'PCA','PCA_vessels_MNI.nii.gz')]);

% Warps PCA vessels into MNI space
system(['applywarp '...
    ' -i ' fullfile(outfolder,subjid,'PCA','PCA_vessels_MNI.nii.gz') ...
    ' -r ' fullfile(outfolder,subjid,'T1w','T1w_acpc_dc_restore.nii.gz') ...
    ' --premat=' fullfile(outfolder,subjid,'T1w','xfms','acpc.mat') ...
    ' --warp=' fullfile(outfolder,subjid,'T1w','BrainExtraction_FNIRTbased','str2standard.nii.gz') ...
    ' -o ' fullfile(outfolder,subjid,'PCA','PCA_vessels_MNI.nii.gz')]);

